name: Run Tests

on:
  # Триггеры: запускать на каждый пуш и pull request
  push:
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Шаг 1: Клонируем ваш репозиторий
      - name: Check out repository
        uses: actions/checkout@v3

      # Шаг 2: Установим Python
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          # укажите версию Python,
          # которая нужна вашему проекту
          python-version: '3.10'

      # Шаг 3: Установим зависимости
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest

      # Шаг 4: Запускаем тесты
      - name: Run tests
        run: |
          pytest --maxfail=1 --disable-warnings -v
